### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Gr3g0ryS/theFirehoseProject-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Gr3g0ryS** [comment]
I'm assuming just add this to the <head> tag ...
<meta name="viewport" content="width=device-width, initial-scale=1">

Implemented and pushed to heroku live as well.

**Comment by kenmazaika** [comment]
Thumbs up!  That's exactly it.  :+1:
